### ISSUE TITLE
Branches have disappeared

### ISSUE THREAD

**Issue by miceno** [dakanji/G2Project-main#72]
Hi

I had made some customizations to the original code from Gallery2 2.3, since I am running a heritage photo site at http://fotos.arxiuhistoricpoblenou.cat. I was interested in merging them in this repo, since I will need PHP 7 support in the future.

Some weeks ago I cloned this repo and there were a different set of branches (like v240-Base, v232-Base, etc...) and now those branches are gone.

Do you have any plans for this project?

Regards.

**Comment by dakanji** [comment]
Hi

I decided to reset how this is setup. As you can see, there has been activity. Give things a little while for me to get the basic PHP 7 going and for the unit tests to be setup.

**Comment by miceno** [comment]
Thank you!

So it is current master brand supporting PHP 7? Or is it a work in progress? The documentation in the  README.mediawiki says it support PHP 7.2.x.

I installed the v2.3.2 release, but I am having some issues installing on php 7.2, but none when installing on php 5.6.

I think I can also help you on migrating part of the code to php 7, if we split the task. I am really interested on it :)

**Comment by dakanji** [comment]
The read me is where it is intended to be soon.

The code "freshness" would be ...
1. Dev
2. Candidate
3. Master 

... in that order.

So new code will done in "stream/abc", "stream/xyz" and so on. These are my local work streams and ultimately, there will be no "stream" branches here

If it looks okay. it will go into "Dev". When it is considered reasonably stable, it will be merged into "Candidate" which is a Release Candidate Branch. When ready for release, this will be merged into "Master".

Everything is however set to v2.3.2 for now which fully supports PHP 5.6.0. When I have finished some initial PHP 7 support  going on on my local machine, this will go into the dev branch. You can then pick that up.
