### ISSUE TITLE
Broken scripts for translations

### ISSUE THREAD

**Issue by miceno** [dakanji/G2Project-main#90]
I was following the procedure described in Gallery2 Codex to translate a module.

While running `make es.po` to get the PO file, I got the following error:
```
../../../lib/tools/po/GNUmakefile.inc:27: *** missing separator.  Stop.
```

It looks like PHP CS Fixer changed the layout of the file.

In order to solve it I have used the original `/lib/tools/po/GNUmakefile.inc` files, and it works without a problem.

Then the problem comes on the `extract.php` file, that has also changed from the original one. I tried it with PHP 7 and PHP 5, and for both it rises an error.

So I finally came up with the original `/lib/tools/po` folder and it works like a charm. 

I will prepare a PR on this.

**Comment by dakanji** [comment]
Picks up discussion in https://github.com/dakanji/G2Project-main/pull/91

**Comment by dakanji** [comment]
On your last comment in the PR, probably the i18n setup is broken ... might be related to eval

**Comment by dakanji** [comment]
The runEval function is not dealing with the situation where the code passed is just expected to return the value as we have in extract.php.

I will implement a solution later today.
