### ISSUE TITLE
Pre-commit script commits all changes of file even if they are not included in commit

### ISSUE THREAD

**Issue by miceno** [dakanji/G2Project-main#92]
Just realized about a problem with the beautifier pre-commit script... I have partially committed the changes I made to a file (`GNUMakefile.inc`), but I didn't include in the commit all the changes I made to the file.

When the `pre-commit` script run, it committed all the changes on `GNUMakefile.inc`.

**Comment by dakanji** [comment]
Aha! I get you now. 

Yes, this is how it is setup indeed as the style rules have to be applied to the file as a whole. Try to avoid only committing hunks.

BTW, it is not just about beautification but the rules enforce other things as well and would be expanded over time. For instance, it would later start to reject usage of certain PHP functions such as `eval` 
 :sunglasses:
